// Generated by `terp routes` from this app's module manifests. Do not edit.
//
// Maps every route path the manifests declare to that route's params and its declared
// query-string keys, so useRouteParams / useRouteParam / useRouteSearch /
// useTerpNavigate check paths, param names and search keys at compile time
// (ADR 0092, ADR 0096). Regenerate after changing a manifest route — `terp verify`
// fails on a stale copy. Routes mounted by a packaged area (the admin area) are not
// keyed here: this file is a pure function of this app's own manifests.

import "@terpjs/react-core";

declare module "@terpjs/react-core" {
  interface TerpRouteTable {
    "/": Record<never, never>;
    "/admin/grants": Record<never, never>;
    "/admin/webhooks": Record<never, never>;
    "/admin/webhooks/deliveries": Record<never, never>;
    "/explorer/devices": Record<never, never>;
    "/explorer/notes": Record<never, never>;
    "/files": Record<never, never>;
    "/journals": Record<never, never>;
    "/projects": Record<never, never>;
    "/tasks": Record<never, never>;
  }
}
