"""create groups tables

Revision ID: bea53bcf1ad4
Revises: 
Create Date: 2026-07-06 14:35:32.454331

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bea53bcf1ad4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_group',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_group'))
    )
    with op.batch_alter_table('user_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_group_name'), ['name'], unique=True)

    op.create_table('user_group_member',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['user_group.id'], name=op.f('fk_user_group_member_group_id_user_group')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_group_member')),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_user_group_member_group_user')
    )
    with op.batch_alter_table('user_group_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_group_member_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_group_member_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_group_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_group_member_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_group_member_group_id'))

    op.drop_table('user_group_member')
    with op.batch_alter_table('user_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_group_name'))

    op.drop_table('user_group')
    # ### end Alembic commands ###
