"""create access tables

Revision ID: 71a140f9930e
Revises: 
Create Date: 2026-06-26 20:38:59.309924

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '71a140f9930e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_grant',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_grant')),
    sa.UniqueConstraint('subject_id', 'permission', name='uq_access_grant_subject_permission')
    )
    with op.batch_alter_table('access_grant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_grant_permission'), ['permission'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_grant_subject_id'), ['subject_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_grant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_grant_subject_id'))
        batch_op.drop_index(batch_op.f('ix_access_grant_permission'))

    op.drop_table('access_grant')
    # ### end Alembic commands ###
