"""create sync tables

Revision ID: cb413566b235
Revises: 
Create Date: 2026-07-01 22:55:48.247941

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb413566b235'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_mapping',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_scope', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('local_id', sa.Uuid(), nullable=False),
    sa.Column('remote_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('remote_checksum', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_mapping')),
    sa.UniqueConstraint('tenant_scope', 'entity_type', 'local_id', name='uq_sync_mapping_local'),
    sa.UniqueConstraint('tenant_scope', 'entity_type', 'remote_id', name='uq_sync_mapping_remote')
    )
    with op.batch_alter_table('sync_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_mapping_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_mapping_local_id'), ['local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_mapping_remote_id'), ['remote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_mapping_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_mapping_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_mapping_tenant_scope'), ['tenant_scope'], unique=False)

    op.create_table('sync_record_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_scope', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('remote_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_record_log'))
    )
    with op.batch_alter_table('sync_record_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_record_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_record_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_record_log_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_record_log_remote_id'), ['remote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_record_log_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_record_log_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_record_log_tenant_scope'), ['tenant_scope'], unique=False)

    op.create_table('sync_run',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_scope', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('cursor', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_run'))
    )
    with op.batch_alter_table('sync_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_run_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_run_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_run_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_run_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_run_tenant_scope'), ['tenant_scope'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_run_tenant_scope'))
        batch_op.drop_index(batch_op.f('ix_sync_run_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_sync_run_status'))
        batch_op.drop_index(batch_op.f('ix_sync_run_started_at'))
        batch_op.drop_index(batch_op.f('ix_sync_run_source'))

    op.drop_table('sync_run')
    with op.batch_alter_table('sync_record_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_record_log_tenant_scope'))
        batch_op.drop_index(batch_op.f('ix_sync_record_log_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_sync_record_log_run_id'))
        batch_op.drop_index(batch_op.f('ix_sync_record_log_remote_id'))
        batch_op.drop_index(batch_op.f('ix_sync_record_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_sync_record_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_sync_record_log_action'))

    op.drop_table('sync_record_log')
    with op.batch_alter_table('sync_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_mapping_tenant_scope'))
        batch_op.drop_index(batch_op.f('ix_sync_mapping_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_sync_mapping_status'))
        batch_op.drop_index(batch_op.f('ix_sync_mapping_remote_id'))
        batch_op.drop_index(batch_op.f('ix_sync_mapping_local_id'))
        batch_op.drop_index(batch_op.f('ix_sync_mapping_entity_type'))

    op.drop_table('sync_mapping')
    # ### end Alembic commands ###
