"""create outbox tables

Revision ID: d0dc58cc803e
Revises: 
Create Date: 2026-06-29 17:34:15.286303

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd0dc58cc803e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dead_lettered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_message'))
    )
    with op.batch_alter_table('outbox_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_message_available_at'), ['available_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_message_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_message_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_message_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_message_locked_by'), ['locked_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_message_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_message_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_message_status'))
        batch_op.drop_index(batch_op.f('ix_outbox_message_name'))
        batch_op.drop_index(batch_op.f('ix_outbox_message_locked_by'))
        batch_op.drop_index(batch_op.f('ix_outbox_message_kind'))
        batch_op.drop_index(batch_op.f('ix_outbox_message_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_outbox_message_created_at'))
        batch_op.drop_index(batch_op.f('ix_outbox_message_available_at'))

    op.drop_table('outbox_message')
    # ### end Alembic commands ###
