"""Code the platform writes into a project passes that project's dependency check.

A generated project declares ``[tool.deptry]``, so ``terp verify --profile full`` runs
deptry over it as a blocking check, and deptry reads every source file the same way,
whoever wrote it. The template itself, ``terp new module`` and ``terp migrate make``
all write Python into a project that its author did not, and between them they
import fastapi, sqlmodel, sqlalchemy and alembic, which the project never declares —
they arrive through terp-core and terp-migrations — while the template exempted only
``terp`` and ``pydantic``. deptry reported the rest as transitive (DEP003), so a new
project failed its merge bar from its first render, and again for each module it
scaffolded and each revision it made.

The writers live in three places — the template, the CLI scaffold, and the revision
template terp-migrations ships — and none of them names the project's deptry table,
which is how they drifted from it. This suite reads what each one writes and holds
every module imported there against the template's ``[project]`` dependencies and
``[tool.deptry]`` table, so an import added to any writer without a matching change
to the template fails here rather than in the first project that runs the check. The
template-acceptance CI job runs deptry itself over a grown project; this is the half
that runs on every ``pytest``.
"""

from __future__ import annotations

import ast
import importlib.metadata
import pathlib
import re
import sys
import tomllib

import pytest
import yaml
from packaging.requirements import Requirement

from terp.cli import _GUIDE_TOPICS, new_module
from terp.cli.profiles import profile_names
from terp.core.migrations import MigrationTree
from terp.migrations import make, orchestrate

# The models the revision is autogenerated from; importing registers their tables.
import terp.capabilities.audit.models  # noqa: F401

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
_PROJECT = _REPO_ROOT / "template" / "project"
_TEMPLATE_PYPROJECT = _PROJECT / "pyproject.toml.jinja"


def _normalise(distribution: str) -> str:
    """PEP 503 name normalisation, so ``SQLAlchemy`` and ``sqlalchemy`` compare equal."""
    return re.sub(r"[-_.]+", "-", distribution).lower()


def _template_deptry() -> dict:
    """The template's ``[tool.deptry]`` tables, parsed as real TOML.

    The manifest is Jinja, not TOML, so it cannot be loaded whole. The deptry tables
    carry no Jinja, so the lines from ``[tool.deptry]`` up to the next table header
    that is not one of its own subtables form a valid document on their own. The
    slice ends at a header rather than at end-of-file so that Jinja added to a LATER
    table cannot break this parse.
    """
    lines = _TEMPLATE_PYPROJECT.read_text(encoding="utf-8").splitlines()
    start = lines.index("[tool.deptry]")
    end = next(
        index
        for index in range(start + 1, len(lines))
        if lines[index].startswith("[") and not lines[index].startswith("[tool.deptry.")
    )
    return tomllib.loads("\n".join(lines[start:end]))["tool"]["deptry"]


def _unconditional_dependencies() -> set[str]:
    """The distributions EVERY generated project declares, read from the Jinja source.

    A requirement inside a ``{% if use_* %}`` block is declared only when that toggle
    is on, while every project renders the template's code, scaffolds and migrates —
    so only a requirement outside every block counts as declared here.
    """
    text = _TEMPLATE_PYPROJECT.read_text(encoding="utf-8")
    block = text[text.index("\ndependencies = [\n") :]
    block = block[: block.index("\n]\n")]
    names: set[str] = set()
    depth = 0
    for line in block.splitlines()[2:]:
        stripped = line.strip()
        if stripped.startswith("{%") and " if " in stripped:
            depth += 1
        elif stripped.startswith("{%") and "endif" in stripped:
            depth -= 1
        elif depth == 0 and stripped.startswith('"'):
            names.add(_normalise(Requirement(stripped.strip('",')).name))
    assert {"terp-core", "terp-migrations"} <= names, (
        f"read {sorted(names)} as the template's unconditional dependencies; the "
        "reader no longer matches template/project/pyproject.toml.jinja"
    )
    return names


def _installed_closure(roots: set[str]) -> set[str]:
    """Every distribution *roots* install, following requirements and requested extras.

    ``pwdlib[argon2]`` installs what pwdlib's ``argon2`` extra names, so each extra a
    requirement asks for is followed too. A requirement whose marker is false here, or
    that belongs to an extra nothing asked for, is not: a plain ``uv sync`` of the
    project would not install it either.
    """
    seen: set[tuple[str, str]] = set()
    pending = [(name, "") for name in roots]
    while pending:
        name, extra = pending.pop()
        if (name, extra) in seen:
            continue
        seen.add((name, extra))
        for spec in importlib.metadata.requires(name) or ():
            requirement = Requirement(spec)
            if requirement.marker is None or requirement.marker.evaluate({"extra": extra}):
                child = _normalise(requirement.name)
                pending.append((child, ""))
                pending.extend((child, requested) for requested in requirement.extras)
    return {name for name, _ in seen}


def _top_level_imports(source: str) -> set[str]:
    """The top-level name of every absolute import in *source*, stdlib excluded."""
    modules: set[str] = set()
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.Import):
            modules.update(alias.name.partition(".")[0] for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
            modules.add(node.module.partition(".")[0])
    return {module for module in modules if module not in sys.stdlib_module_names}


def _without_jinja(text: str) -> str:
    """*text* with every Jinja tag dropped and every Jinja expression replaced by a name.

    Dropping the tags keeps every branch of every ``{% if %}`` at once, which is what
    this suite wants: the union of what any combination of answers renders.
    """
    return re.sub(r"\{\{.*?\}\}", "x", re.sub(r"\{%.*?%\}", "", text))


def _unaccounted(imports_by_source: dict[str, set[str]]) -> dict[str, list[str]]:
    """Each imported module the template does not account for, with who imports it.

    deptry passes a module that is first-party or that a declared distribution
    provides. A module a declared distribution only installs transitively passes when
    it is listed under DEP003; one that no declared distribution installs is DEP001,
    or DEP004 when only a dev dependency provides it, and that list covers neither.
    """
    deptry = _template_deptry()
    first_party = set(deptry["known_first_party"])
    exempt = set(deptry["per_rule_ignores"]["DEP003"])
    declared = _unconditional_dependencies()
    installed = _installed_closure(declared)
    providers = importlib.metadata.packages_distributions()
    # This workspace installs the terp-* distributions editable, and an editable
    # install records no top-level module, so the namespace they share can be missing
    # from the map above. In a generated project they are wheels and deptry maps `terp`
    # to them; this maps it the same way, by the distributions' names.
    providers.setdefault("terp", [name for name in installed if name.startswith("terp-")])

    def accounted_for(module: str) -> bool:
        provided_by = {_normalise(name) for name in providers.get(module, ())}
        return (
            module in first_party
            or bool(provided_by & declared)
            or (module in exempt and bool(provided_by & installed))
        )

    missing: dict[str, list[str]] = {}
    for source, modules in sorted(imports_by_source.items()):
        for module in sorted(modules):
            if not accounted_for(module):
                missing.setdefault(module, []).append(source)
    return missing


def _explain(writer: str, missing: dict[str, list[str]]) -> str:
    listing = "; ".join(
        f"{module} (imported by {', '.join(sources)})" for module, sources in missing.items()
    )
    return (
        f"{writer} writes imports that template/project/pyproject.toml.jinja does not "
        f"account for: {listing}. A generated project runs deptry in `terp verify "
        "--profile full`, so each one fails its merge bar (DEP003 when a declared "
        "dependency installs it transitively, DEP001 or DEP004 otherwise). A module "
        "the platform writes an import of must be first-party, provided by a declared "
        "dependency, or listed in [tool.deptry.per_rule_ignores] DEP003 while a "
        "declared dependency installs it: add it to that list with the reason, or drop "
        "the import."
    )


def test_the_templates_own_code_imports_only_what_the_template_accounts_for() -> None:
    # deptry's default exclude drops the project's top-level `tests/`, and so does this.
    sources = sorted(
        path
        for pattern in ("*.py", "*.py.jinja")
        for path in _PROJECT.rglob(pattern)
        if path.relative_to(_PROJECT).parts[0] != "tests"
    )
    imports = {
        path.relative_to(_PROJECT).as_posix(): _top_level_imports(
            _without_jinja(path.read_text(encoding="utf-8"))
        )
        for path in sources
    }
    # The composition root imports the kernel, so a reader that found no `terp` import
    # anywhere is broken, and would otherwise pass this test by finding nothing.
    assert "terp" in imports.get("app/main.py.jinja", set()), f"parsed {imports}"
    missing = _unaccounted(imports)
    assert not missing, _explain("the template", missing)


@pytest.mark.parametrize("profile", profile_names())
def test_a_scaffolded_module_imports_only_what_the_template_accounts_for(
    profile: str, tmp_path: pathlib.Path
) -> None:
    written = new_module("records", root=tmp_path, frontend=False, profile=profile)
    imports = {
        path.relative_to(tmp_path).as_posix(): _top_level_imports(path.read_text(encoding="utf-8"))
        for path in written
        if path.suffix == ".py" and path.relative_to(tmp_path).parts[0] != "tests"
    }
    # Every scaffolded module is built on the kernel's base classes.
    assert any("terp" in modules for modules in imports.values()), f"parsed {imports}"
    missing = _unaccounted(imports)
    assert not missing, _explain(f"`terp new module --profile {profile}`", missing)


def test_a_new_revision_imports_only_what_the_template_accounts_for(
    tmp_path: pathlib.Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # A real `make`, autogenerated against real models into a throwaway tree, so what is
    # parsed is exactly what lands in a project: the revision template's own imports
    # plus any that autogenerate adds for the types it renders.
    tree = MigrationTree("audit", "terp.capabilities.audit", tmp_path / "migrations")
    monkeypatch.setattr(orchestrate, "resolve_migration_target", lambda *a, **k: tree)
    make("audit", "create audit", f"sqlite:///{tmp_path / 'make.db'}", autogenerate=True)
    (revision,) = (tmp_path / "migrations" / "versions").glob("*.py")
    imported = _top_level_imports(revision.read_text(encoding="utf-8"))
    # Every autogenerated revision calls `op.*`, so a parse that found no alembic import
    # is a broken reader, and would otherwise pass this test by finding nothing.
    assert "alembic" in imported, f"parsed {sorted(imported)} from {revision.name}"
    missing = _unaccounted({f"migrations/versions/{revision.name}": imported})
    assert not missing, _explain(
        "`terp migrate make` (packages/backend/migrations/src/terp/migrations/"
        "_alembic/script.py.mako)",
        missing,
    )


def test_the_dependency_hygiene_guide_teaches_the_templates_exemptions() -> None:
    # `terp guide dependency-hygiene` hands an existing project the table to adopt and
    # says a generated project already has it. A list there that fell behind the
    # template would hand that project the failure this suite exists to prevent.
    match = re.search(
        r"^\s*DEP003 = (\[.*\])$", _GUIDE_TOPICS["dependency-hygiene"], re.MULTILINE
    )
    assert match, "`terp guide dependency-hygiene` no longer shows a DEP003 list"
    taught = ast.literal_eval(match.group(1))
    exempt = _template_deptry()["per_rule_ignores"]["DEP003"]
    assert taught == exempt, (
        f"`terp guide dependency-hygiene` teaches DEP003 = {taught}, while "
        f"template/project/pyproject.toml.jinja exempts {exempt}; the two must move "
        "together"
    )


def test_template_acceptance_runs_deptry_after_the_first_revision() -> None:
    """The real tool over real output, pinned so that removing it is a visible edit.

    The tests above model deptry's rules; only deptry decides them. So the CI step that
    grows a rendered project, scaffolding a module and making its first revision, runs
    deptry once that revision exists — the one place the actual tool reads the
    template's code, a scaffolded module and a revision together.
    """
    workflow = yaml.safe_load(
        (_REPO_ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")
    )
    steps = workflow["jobs"]["template-acceptance"]["steps"]
    (grow,) = [step for step in steps if "terp migrate make" in step.get("run", "")]
    lines = [line.strip() for line in grow["run"].splitlines()]
    made = next(i for i, line in enumerate(lines) if line.startswith("uv run terp migrate make"))
    assert "uv run deptry ." in lines[made + 1 :], (
        f"the template-acceptance step {grow['name']!r} no longer runs `uv run deptry .` "
        "after `terp migrate make`, so nothing runs the real tool over a generated project "
        "that holds a scaffolded module and a revision"
    )
