"""create journals tables

Revision ID: 6a0738d075b7
Revises: 
Create Date: 2026-06-28 10:49:46.160256

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a0738d075b7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal',
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('entry', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal'))
    )
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_title'))
        batch_op.drop_index(batch_op.f('ix_journal_owner_id'))

    op.drop_table('journal')
    # ### end Alembic commands ###
