"""create tasks tables

Revision ID: 779bea252085
Revises: 
Create Date: 2026-06-26 20:38:59.526456

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '779bea252085'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('modified_by_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_modified_by_id'), ['modified_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_title'))
        batch_op.drop_index(batch_op.f('ix_task_status'))
        batch_op.drop_index(batch_op.f('ix_task_modified_by_id'))
        batch_op.drop_index(batch_op.f('ix_task_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_task_created_by_id'))

    op.drop_table('task')
    # ### end Alembic commands ###
