"""create audit tables

Revision ID: 586333320cdd
Revises: 
Create Date: 2026-06-26 20:38:59.070766

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '586333320cdd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event'))
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_event_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_target_type'), ['target_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_event_target_type'))
        batch_op.drop_index(batch_op.f('ix_audit_event_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_event_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_action'))

    op.drop_table('audit_event')
    # ### end Alembic commands ###
