"""create identity refresh_token table

Revision ID: b7e2f4a19c6d
Revises: c753c4d79af2
Create Date: 2026-07-01 21:30:00.000000

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b7e2f4a19c6d'
down_revision: str | None = 'c753c4d79af2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_refresh_token',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('family_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_refresh_token'))
    )
    with op.batch_alter_table('identity_refresh_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_refresh_token_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_refresh_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_identity_refresh_token_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity_refresh_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_refresh_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_identity_refresh_token_token_hash'))
        batch_op.drop_index(batch_op.f('ix_identity_refresh_token_family_id'))

    op.drop_table('identity_refresh_token')
    # ### end Alembic commands ###
