"""create webhooks tables

Revision ID: 717754ab63f6
Revises: 
Create Date: 2026-06-30 22:16:37.385448

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '717754ab63f6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_delivery',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_delivery'))
    )
    with op.batch_alter_table('webhook_delivery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_delivery_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_delivery_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_delivery_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_delivery_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('webhook_subscription',
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('target_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('secret', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_subscription'))
    )
    with op.batch_alter_table('webhook_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_subscription_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_subscription_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_subscription_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_subscription_target_url'), ['target_url'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_subscription_target_url'))
        batch_op.drop_index(batch_op.f('ix_webhook_subscription_owner_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_subscription_event'))
        batch_op.drop_index(batch_op.f('ix_webhook_subscription_active'))

    op.drop_table('webhook_subscription')
    with op.batch_alter_table('webhook_delivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_delivery_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_delivery_outcome'))
        batch_op.drop_index(batch_op.f('ix_webhook_delivery_event'))
        batch_op.drop_index(batch_op.f('ix_webhook_delivery_created_at'))

    op.drop_table('webhook_delivery')
    # ### end Alembic commands ###
