"""create lease table

Revision ID: d80d25cf8092
Revises:
Create Date: 2026-08-20 09:00:00.000000

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd80d25cf8092'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_lease',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_kind', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('resource_key', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('holder', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('touched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_lease')),
    sa.UniqueConstraint('resource_kind', 'resource_key', name='uq_resource_lease_resource')
    )
    with op.batch_alter_table('resource_lease', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_lease_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_lease_holder'), ['holder'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_lease_resource_kind'), ['resource_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_lease_touched_at'), ['touched_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_lease', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_lease_touched_at'))
        batch_op.drop_index(batch_op.f('ix_resource_lease_resource_kind'))
        batch_op.drop_index(batch_op.f('ix_resource_lease_holder'))
        batch_op.drop_index(batch_op.f('ix_resource_lease_expires_at'))

    op.drop_table('resource_lease')
    # ### end Alembic commands ###
