#!/usr/bin/env node
/**
 * `terp-routes` — emit an app's route types from its module manifests (ADR 0092).
 *
 * A Terp app's router is built at RUNTIME from manifest data, so TanStack Router's
 * type registry is empty and nothing checks a route path or a param name: the raw read
 * was an unchecked cast, and a typo'd path was a dead link that shipped green. The
 * information to check them is already checked in — `routes` is a static array of
 * object literals — so this generator extracts it and writes a committed
 * `src/routes.gen.d.ts` that augments `TerpRouteTable` in @terpjs/react-core.
 *
 * Extraction is FAIL CLOSED, which is the whole point: a route whose `path` is not a
 * plain string literal (a template literal, a constant, a spread) cannot be read
 * statically, so the generator refuses and NAMES it instead of quietly emitting a
 * partial map — a table missing a route is worse than no table, because it turns a real
 * path into a type error and teaches authors to distrust the check.
 *
 * Scope is the app's own manifests (`src/modules/<name>/module.tsx`). Routes a packaged
 * area mounts (react-core's admin area) are deliberately NOT keyed: the artifact stays a
 * pure function of the app's own source, so it never drifts because a dependency's
 * internals changed. Link to those paths with `Link` / the router's own `navigate`.
 *
 * Usage:
 *   terp-routes                      # write src/routes.gen.d.ts
 *   terp-routes --check              # exit non-zero when the committed file is stale
 *   terp-routes --out <file> --modules-dir <dir>
 */

import fs from "node:fs";
import path from "node:path";

import ts from "typescript";

/** The declaration file's header — states what regenerates it, so an editor stops. */
const HEADER = [
  "// Generated by `terp routes` from this app's module manifests. Do not edit.",
  "//",
  "// Maps every route path the manifests declare to that route's params and its declared",
  "// query-string keys, so useRouteParams / useRouteParam / useRouteSearch /",
  "// useTerpNavigate check paths, param names and search keys at compile time",
  "// (ADR 0092, ADR 0096). Regenerate after changing a manifest route — `terp verify`",
  "// fails on a stale copy. Routes mounted by a packaged area (the admin area) are not",
  "// keyed here: this file is a pure function of this app's own manifests.",
  "",
  'import "@terpjs/react-core";',
  "",
  'declare module "@terpjs/react-core" {',
  "  interface TerpRouteTable {",
];

/** Param names a manifest path declares, in order. Both dialects: `:id` and `$id`. */
export function paramNamesOf(routePath) {
  return [...routePath.matchAll(/(?:^|\/)[:$]([A-Za-z_][A-Za-z0-9_]*)/g)].map((match) => match[1]);
}

/** The canonical table key: the manifest's stack-agnostic spelling (`:id`). */
export function canonicalPath(routePath) {
  return routePath.replace(/(^|\/)\$([A-Za-z_][A-Za-z0-9_]*)/g, "$1:$2");
}

/** Find a property assignment by name on an object literal, or undefined. */
function propertyNamed(element, name) {
  return element.properties.find(
    (property) =>
      ts.isPropertyAssignment(property) &&
      (ts.isIdentifier(property.name) || ts.isStringLiteral(property.name)) &&
      property.name.text === name,
  );
}

/**
 * Every route a source file's `defineModuleManifest(...)` calls declare.
 *
 * Returns `{ routes, problems }`, where a route is `{ path, search }`. A shape that
 * cannot be read statically lands in `problems` (with file:line) rather than being
 * skipped — the caller refuses on any. `search` is held to the same standard as `path`:
 * a computed key list is refused rather than silently dropped, because a missing search
 * key turns a real navigation into a type error, which is the failure mode that teaches
 * authors to distrust the check.
 */
export function extractRoutes(sourceText, label) {
  const source = ts.createSourceFile(label, sourceText, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
  const routes = [];
  const problems = [];
  let manifests = 0;

  const at = (node) => {
    const { line } = source.getLineAndCharacterOfPosition(node.getStart(source));
    return `${label}:${line + 1}`;
  };

  const readRoutesArray = (routesValue) => {
    if (!ts.isArrayLiteralExpression(routesValue)) {
      problems.push(
        `${at(routesValue)}: \`routes\` is not an array literal, so its paths cannot be read ` +
          "statically. Declare the routes inline in defineModuleManifest(...).",
      );
      return;
    }
    for (const element of routesValue.elements) {
      if (!ts.isObjectLiteralExpression(element)) {
        problems.push(
          `${at(element)}: a route is not an object literal (a spread or a reference?), so its ` +
            "path cannot be read statically. Declare each route inline.",
        );
        continue;
      }
      const pathProperty = propertyNamed(element, "path");
      if (pathProperty === undefined) {
        problems.push(`${at(element)}: a route declares no \`path\`.`);
        continue;
      }
      const value = pathProperty.initializer;
      if (!ts.isStringLiteral(value)) {
        problems.push(
          `${at(value)}: a route \`path\` is not a plain string literal, so it cannot be read ` +
            "statically. Write the path inline (e.g. path: \"/records/:recordId\").",
        );
        continue;
      }
      const search = readSearchKeys(element);
      if (search === null) {
        continue;
      }
      routes.push({ path: value.text, search });
    }
  };

  /** A route's declared query-string keys, `[]` when it declares none, `null` on refusal. */
  const readSearchKeys = (element) => {
    const searchProperty = propertyNamed(element, "search");
    if (searchProperty === undefined) {
      return [];
    }
    const value = searchProperty.initializer;
    if (!ts.isArrayLiteralExpression(value)) {
      problems.push(
        `${at(value)}: a route \`search\` is not an array literal, so its keys cannot be read ` +
          'statically. Write them inline (e.g. search: ["status", "page"]).',
      );
      return null;
    }
    const keys = [];
    for (const key of value.elements) {
      if (!ts.isStringLiteral(key)) {
        problems.push(
          `${at(key)}: a route \`search\` key is not a plain string literal, so it cannot be ` +
            'read statically. Write each key inline (e.g. search: ["status", "page"]).',
        );
        return null;
      }
      if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key.text)) {
        problems.push(
          `${at(key)}: search key ${JSON.stringify(key.text)} is not a plain identifier, so it ` +
            "cannot be emitted as a typed property. Rename it to letters, digits and " +
            "underscores.",
        );
        return null;
      }
      keys.push(key.text);
    }
    return keys;
  };

  const visit = (node) => {
    if (
      ts.isCallExpression(node) &&
      ((ts.isIdentifier(node.expression) && node.expression.text === "defineModuleManifest") ||
        (ts.isPropertyAccessExpression(node.expression) &&
          node.expression.name.text === "defineModuleManifest"))
    ) {
      manifests += 1;
      const [argument] = node.arguments;
      if (argument === undefined || !ts.isObjectLiteralExpression(argument)) {
        problems.push(
          `${at(node)}: defineModuleManifest was not called with an object literal, so its routes ` +
            "cannot be read statically.",
        );
      } else {
        const declared = propertyNamed(argument, "routes");
        if (declared === undefined) {
          problems.push(`${at(argument)}: the manifest declares no \`routes\`.`);
        } else {
          readRoutesArray(declared.initializer);
        }
      }
    }
    ts.forEachChild(node, visit);
  };
  visit(source);

  if (manifests === 0) {
    problems.push(
      `${label}: no defineModuleManifest(...) call found. A module slot declares its routes there; ` +
        "a module whose manifest is built elsewhere cannot be extracted.",
    );
  }
  return { routes, problems };
}

/** The module files to scan: `<modulesDir>/<name>/module.tsx` (or `.ts`), sorted. */
export function moduleFiles(modulesDir) {
  if (!fs.existsSync(modulesDir)) {
    return [];
  }
  const found = [];
  for (const entry of fs.readdirSync(modulesDir, { withFileTypes: true }).sort((a, b) => (a.name < b.name ? -1 : 1))) {
    if (!entry.isDirectory()) {
      continue;
    }
    for (const basename of ["module.tsx", "module.ts"]) {
      const candidate = path.join(modulesDir, entry.name, basename);
      if (fs.existsSync(candidate)) {
        found.push(candidate);
        break;
      }
    }
  }
  return found;
}

/** Render the declaration file for *routes* — deterministic: deduped, sorted, LF. */
export function renderRouteTable(routes) {
  // Two manifests may mount the same path; their declared search keys are unioned, which
  // is the honest reading of "this route reads these keys".
  const searchByPath = new Map();
  for (const route of routes) {
    const key = canonicalPath(route.path);
    const merged = searchByPath.get(key) ?? [];
    searchByPath.set(key, [...merged, ...(route.search ?? [])]);
  }
  const unique = [...searchByPath.keys()].sort();

  const lines = [...HEADER];
  for (const routePath of unique) {
    const params = paramNamesOf(routePath);
    const shape =
      params.length === 0
        ? "Record<never, never>"
        : `{ ${params.map((name) => `${name}: string`).join("; ")} }`;
    lines.push(`    ${JSON.stringify(routePath)}: ${shape};`);
  }
  lines.push("  }");

  // Only emitted when some route declares keys: an app that declares none gets exactly
  // the file it had before, and no empty interface for its own linter to complain about.
  const withSearch = unique.filter((routePath) => searchByPath.get(routePath).length > 0);
  if (withSearch.length > 0) {
    lines.push("  interface TerpRouteSearchTable {");
    for (const routePath of withSearch) {
      const keys = [...new Set(searchByPath.get(routePath))].sort();
      const shape = keys.map((name) => `${name}?: string`).join("; ");
      lines.push(`    ${JSON.stringify(routePath)}: { ${shape} };`);
    }
    lines.push("  }");
  }
  lines.push("}", "");
  return lines.join("\n");
}

/**
 * Extract from every module file under *modulesDir* and render the declaration file.
 * Throws with every problem listed when any route resists static reading (fail closed).
 */
export function generateRouteTable(modulesDir) {
  const files = moduleFiles(modulesDir);
  if (files.length === 0) {
    throw new Error(
      `No module slots found under ${modulesDir}. A Terp app declares its routes in ` +
        "src/modules/<name>/module.tsx; pass --modules-dir if this app keeps them elsewhere.",
    );
  }
  const routes = [];
  const problems = [];
  for (const file of files) {
    const result = extractRoutes(fs.readFileSync(file, "utf8"), path.relative(process.cwd(), file).split(path.sep).join("/"));
    routes.push(...result.routes);
    problems.push(...result.problems);
  }
  if (problems.length > 0) {
    throw new Error(
      "terp routes refused to emit a partial route table — every route must be readable " +
        "statically, or the generated types would turn a real path into a type error:\n" +
        problems.map((problem) => `  - ${problem}`).join("\n"),
    );
  }
  return renderRouteTable(routes);
}

/** Parse `--flag value` / `--flag` argv into a plain object. */
function parseArgs(argv) {
  const options = { out: "src/routes.gen.d.ts", modulesDir: "src/modules", check: false };
  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];
    if (argument === "--check") {
      options.check = true;
    } else if (argument === "--out") {
      options.out = argv[(index += 1)];
    } else if (argument === "--modules-dir") {
      options.modulesDir = argv[(index += 1)];
    } else {
      throw new Error(`terp-routes: unknown argument ${argument}`);
    }
  }
  if (options.out === undefined || options.modulesDir === undefined) {
    throw new Error("terp-routes: --out and --modules-dir need a value");
  }
  return options;
}

/** The CLI: write the table, or (with --check) refuse a stale committed copy. */
export function run(argv, { cwd = process.cwd(), log = console.log } = {}) {
  const options = parseArgs(argv);
  const outPath = path.resolve(cwd, options.out);
  const rendered = generateRouteTable(path.resolve(cwd, options.modulesDir));
  const onDisk = fs.existsSync(outPath) ? fs.readFileSync(outPath, "utf8") : null;

  if (options.check) {
    if (onDisk === rendered) {
      log(`terp routes: ${options.out} is current`);
      return 0;
    }
    log(
      `${options.out} is ${onDisk === null ? "missing" : "stale"} — the module manifests declare ` +
        "different routes than the committed route table.\nFix: npm --prefix frontend run routes " +
        "(or `uv run terp routes`), then commit the regenerated file.",
    );
    return 1;
  }

  if (onDisk === rendered) {
    log(`terp routes: ${options.out} unchanged`);
    return 0;
  }
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  // newline unchanged: the rendered text is LF-only, so the committed artifact stays
  // byte-stable on Windows and the --check comparison never trips on line endings.
  fs.writeFileSync(outPath, rendered, "utf8");
  log(`terp routes: wrote ${options.out}`);
  return 0;
}

// No self-executing guard here on purpose: `bin/terp-routes.js` is the entry point. An
// `import.meta.url === argv[1]` check does not hold when npm invokes the bin through its
// shim, and it fails by doing nothing at exit 0 — a check that silently never checks.
