/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/access/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the permissions granted to someone */
        get: operations["access.list_grants"];
        put?: never;
        /** Grant a permission to someone */
        post: operations["access.create_grant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access/grants/{grant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a granted permission */
        delete: operations["access.delete_grant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * See which roles exist and what each one may do
         * @description The declared authority surface: the ladder, the permissions, and every module.
         *
         *     The read half of a permission editor, and the reason the projection it is built on moved
         *     into the kernel: this capability cannot import ``terp.cli``, where ``terp inspect access``
         *     lives. One builder, so the pane and the audit view cannot disagree about who may do what.
         *
         *     Derivation over what ``create_app`` recorded on ``app.state`` — no database read at all,
         *     which is why it says nothing about *who holds* anything. That question needs the grant
         *     rows and is a different endpoint.
         *
         *     Admin-only, through this module's own ``Policy``. The permission topology is a map of
         *     where the doors are, so it is not something an under-privileged caller should be able to
         *     enumerate; a caller asking what *they themselves* may do is answered by ``GET /me``
         *     (ADR 0096), which needs no privilege because it only ever reports the caller's own.
         */
        get: operations["access.get_model"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access/subjects/{subject_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * See what someone can do, and where each right comes from
         * @description One subject's effective access, with the provenance of every right.
         *
         *     "Why can this person do that?" is the question an administrator has to be able to answer
         *     before any of this is safe, and it is the one a matrix of effective answers cannot answer
         *     on its own. Every row here names the subject it came from — the person themselves, or a
         *     group they belong to — because a right whose origin is unknown is a right nobody can
         *     remove with confidence.
         *
         *     Two things are reported rather than filtered. A grant naming a permission the app no
         *     longer declares comes back with ``declared: false``, and a module role at an undeclared
         *     rank or in a module that no longer accepts them comes back with its reason in ``stale`` —
         *     on the reasoning ``terp grant list`` gives, that a filtered row is a right nobody can
         *     explain. And where several module rows exist for one module, only the highest is marked
         *     ``effective``, which is the thing most often misread: assigning a lower rung alongside a
         *     higher one changes nothing at all.
         */
        get: operations["access.get_subject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View the audit trail */
        get: operations["audit.list_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with an email and password */
        post: operations["auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out of the current session */
        post: operations["auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stay signed in without entering a password again */
        post: operations["auth.refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the groups */
        get: operations["groups.list_groups"];
        put?: never;
        /** Create a new group */
        post: operations["groups.create_group"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View a group's details */
        get: operations["groups.get_group"];
        put?: never;
        post?: never;
        /** Delete a group */
        delete: operations["groups.delete_group"];
        options?: never;
        head?: never;
        /** Change a group's details */
        patch: operations["groups.update_group"];
        trace?: never;
    };
    "/api/v1/groups/{group_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List who belongs to a group */
        get: operations["groups.list_members"];
        put?: never;
        /** Add someone to a group */
        post: operations["groups.add_member"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{group_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove someone from a group */
        delete: operations["groups.remove_member"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View your own profile */
        get: operations["auth.me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every user account */
        get: operations["users.list_users"];
        put?: never;
        /** Create a new user account */
        post: operations["users.provision_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View a user account's details */
        get: operations["users.get_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change a user account's details */
        patch: operations["users.update_user"];
        trace?: never;
    };
    "/api/v1/users/{user_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable a user account without deleting it */
        post: operations["users.deactivate_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-enable a disabled user account */
        post: operations["users.reactivate_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password for a user */
        post: operations["users.reset_user_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description Liveness: the process is up. No dependency is checked.
         */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness: 200 when the database answers ``SELECT 1``, else 503.
         */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccessEndpointRead
         * @description One mounted route and the authority that applies to it.
         */
        AccessEndpointRead: {
            /** By Role */
            by_role: components["schemas"]["AccessRoleOutcomeRead"][];
            /** Extra Permissions */
            extra_permissions: string[];
            /** Methods */
            methods: string[];
            /** Name */
            name: string;
            operation: components["schemas"]["AccessOperationRead"] | null;
            /** Path */
            path: string;
            /** Requirement */
            requirement: string;
        };
        /**
         * AccessModelRead
         * @description The declared authority surface: the ladder, the permissions, and every module.
         */
        AccessModelRead: {
            /** Modules */
            modules: components["schemas"]["AccessModuleRead"][];
            /** Permissions */
            permissions: components["schemas"]["AccessPermissionRead"][];
            /** Roles */
            roles: components["schemas"]["AccessRoleRead"][];
        };
        /**
         * AccessModuleRead
         * @description One module's declared authority.
         */
        AccessModuleRead: {
            access: components["schemas"]["ModuleAccessRead"] | null;
            /** Endpoints */
            endpoints: components["schemas"]["AccessEndpointRead"][];
            /** Name */
            name: string;
            /** Permissions */
            permissions: string[];
            policy: components["schemas"]["AccessPolicyRead"] | null;
            /** Prefix */
            prefix: string | null;
        };
        /**
         * AccessOperationRead
         * @description What a route does, in the source language (ADR 0102).
         */
        AccessOperationRead: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /**
         * AccessPermissionRead
         * @description One declared permission: its name, its rank floor, and what holding it buys.
         */
        AccessPermissionRead: {
            /** Label */
            label: string | null;
            /** Min Role */
            min_role: string;
            /** Name */
            name: string;
        };
        /**
         * AccessPolicyRead
         * @description A module's declared posture. ``public`` decides which of the other fields apply.
         */
        AccessPolicyRead: {
            /** Allows Public Writes */
            allows_public_writes?: boolean | null;
            /** Authenticated */
            authenticated?: boolean | null;
            /** Public */
            public: boolean;
            /** Public Reason */
            public_reason?: string | null;
            /** Read */
            read?: string | null;
            /** Write */
            write?: string | null;
        };
        /**
         * AccessRoleOutcomeRead
         * @description What one rung gets on one route, replayed through the kernel guard's own decision.
         */
        AccessRoleOutcomeRead: {
            /** Allowed */
            allowed: boolean;
            /** Reason */
            reason: string;
            /** Role */
            role: string;
        };
        /**
         * AccessRoleRead
         * @description One rung of the app's declared ladder.
         */
        AccessRoleRead: {
            /** Name */
            name: string;
            /** Rank */
            rank: number;
        };
        /** AccessToken */
        AccessToken: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** AuditEventRead */
        AuditEventRead: {
            /** Action */
            action: string;
            /** Actor Id */
            actor_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            } | null;
            /** Request Id */
            request_id: string | null;
            /** Target Id */
            target_id: string;
            /** Target Type */
            target_type: string;
        };
        /**
         * CurrentUser
         * @description The authenticated caller's own identity — the ``/me`` (who-am-I) response.
         *
         *     The frontend's session contract pairs this with :class:`AccessToken`. It is the
         *     server-validated current identity (resolved through the wired principal provider —
         *     the revocable one in the bundled stack), so it reflects the live store, not just the
         *     token's claims. The caller's role is on the wire as both the numeric ``role_rank``
         *     (the comparable primitive, ADR 0004 / 0022) and a human-readable ``role_name``.
         */
        CurrentUser: {
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Permissions
             * @default []
             */
            permissions: string[];
            /** Role Name */
            role_name: string;
            /** Role Rank */
            role_rank: number;
        };
        /** GrantCreate */
        GrantCreate: {
            /** Permission */
            permission: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
        };
        /** GrantRead */
        GrantRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Permission */
            permission: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** GroupCreate */
        GroupCreate: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
        };
        /** GroupMemberAdd */
        GroupMemberAdd: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** GroupMemberRead */
        GroupMemberRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email?: string | null;
            /**
             * Group Id
             * Format: uuid
             */
            group_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** GroupRead */
        GroupRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Member Count */
            member_count: number;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** GroupUpdate */
        GroupUpdate: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
            /**
             * Version
             * @description Version from the most recent read response, used for optimistic concurrency control. A stale value is rejected with HTTP 409.
             */
            version: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeldModuleRoleRead
         * @description One per-module rung a subject holds, and why.
         */
        HeldModuleRoleRead: {
            /** Effective */
            effective: boolean;
            /** Module */
            module: string;
            /** Role */
            role: string | null;
            /** Role Rank */
            role_rank: number;
            /** Stale */
            stale: string[];
            via: components["schemas"]["SubjectRefRead"];
        };
        /**
         * HeldPermissionRead
         * @description One permission a subject holds, and why.
         */
        HeldPermissionRead: {
            /** Declared */
            declared: boolean;
            /** Label */
            label: string | null;
            /** Name */
            name: string;
            via: components["schemas"]["SubjectRefRead"];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * ModuleAccessRead
         * @description Whether a module takes part in per-module role assignment (ADR 0112).
         */
        ModuleAccessRead: {
            /** Assignable */
            assignable: boolean;
            /** Label */
            label: string | null;
            /** Platform Reason */
            platform_reason: string | null;
            /** Summary */
            summary: string | null;
        };
        /** Page[AuditEventRead] */
        Page_AuditEventRead_: {
            /** Items */
            items: components["schemas"]["AuditEventRead"][];
            /** Limit */
            limit: number;
            /** Skip */
            skip: number;
            /** Total */
            total: number;
        };
        /** Page[GrantRead] */
        Page_GrantRead_: {
            /** Items */
            items: components["schemas"]["GrantRead"][];
            /** Limit */
            limit: number;
            /** Skip */
            skip: number;
            /** Total */
            total: number;
        };
        /** Page[GroupMemberRead] */
        Page_GroupMemberRead_: {
            /** Items */
            items: components["schemas"]["GroupMemberRead"][];
            /** Limit */
            limit: number;
            /** Skip */
            skip: number;
            /** Total */
            total: number;
        };
        /** Page[GroupRead] */
        Page_GroupRead_: {
            /** Items */
            items: components["schemas"]["GroupRead"][];
            /** Limit */
            limit: number;
            /** Skip */
            skip: number;
            /** Total */
            total: number;
        };
        /** Page[UserRead] */
        Page_UserRead_: {
            /** Items */
            items: components["schemas"]["UserRead"][];
            /** Limit */
            limit: number;
            /** Skip */
            skip: number;
            /** Total */
            total: number;
        };
        /**
         * SubjectAccessRead
         * @description One subject's effective access, with the provenance of every right.
         *
         *     The answer to "why can this person do that?", which is the only defence an administrator
         *     has against an over-broad grant. It reports what is *held*; what that lets someone do on a
         *     given route is the declared model's question (``GET /model``), and a pane joins the two.
         *
         *     It deliberately does **not** carry the subject's global rank. That lives in the users
         *     table, which this capability cannot import — its whole premise is being a leaf the
         *     identity modules depend on rather than the reverse — and a field nothing here could ever
         *     fill would be structurally null. A pane already fetches the account to show its detail
         *     screen, so it has the rank; adding a seam to duplicate it here would be a second source
         *     of truth for one integer.
         */
        SubjectAccessRead: {
            /** Module Roles */
            module_roles: components["schemas"]["HeldModuleRoleRead"][];
            /** Permissions */
            permissions: components["schemas"]["HeldPermissionRead"][];
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Via */
            via: components["schemas"]["SubjectRefRead"][];
        };
        /**
         * SubjectRefRead
         * @description Where a right came from: the caller themselves, or a group they belong to.
         */
        SubjectRefRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string | null;
        };
        /**
         * UserAdminUpdate
         * @description Admin edits a user's email / role rank (OCC ``version`` required).
         *
         *     Activation state is changed through the dedicated ``deactivate`` /
         *     ``reactivate`` actions, not this generic patch.
         */
        UserAdminUpdate: {
            /** Email */
            email?: string | null;
            /** Role */
            role?: number | null;
            /**
             * Version
             * @description Version from the most recent read response, used for optimistic concurrency control. A stale value is rejected with HTTP 409.
             */
            version: number;
        };
        /**
         * UserPasswordReset
         * @description Admin sets a new password for a user.
         */
        UserPasswordReset: {
            /** Password */
            password: string;
        };
        /**
         * UserProvision
         * @description Admin-provisions a new user with an initial password and a role *rank*.
         *
         *     ``role`` is an integer rank resolved against the app's ``PermissionModel`` at
         *     login (ADR 0022), so an admin can provision any role the app's ladder defines —
         *     not only the default three tiers; an unmodeled rank simply fails closed at that
         *     user's next login. The default is the viewer rank.
         */
        UserProvision: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default 10
             */
            role: number;
        };
        /** UserRead */
        UserRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Role */
            role: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "access.list_grants": {
        parameters: {
            query: {
                subject_id: string;
                /** @description Rows to skip. */
                skip?: number;
                /** @description Maximum rows to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_GrantRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "access.create_grant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "access.delete_grant": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "access.get_model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessModelRead"];
                };
            };
        };
    };
    "access.get_subject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectAccessRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "audit.list_events": {
        parameters: {
            query?: {
                /** @description Rows to skip. */
                skip?: number;
                /** @description Maximum rows to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditEventRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "auth.refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
        };
    };
    "groups.list_groups": {
        parameters: {
            query?: {
                /** @description Rows to skip. */
                skip?: number;
                /** @description Maximum rows to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_GroupRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "groups.create_group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "groups.get_group": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "groups.delete_group": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "groups.update_group": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "groups.list_members": {
        parameters: {
            query?: {
                /** @description Rows to skip. */
                skip?: number;
                /** @description Maximum rows to return. */
                limit?: number;
            };
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_GroupMemberRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "groups.add_member": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupMemberAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMemberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "groups.remove_member": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "auth.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
        };
    };
    "users.list_users": {
        parameters: {
            query?: {
                /** @description Filter to users whose email contains this text (case-insensitive). */
                email?: string | null;
                /** @description Rows to skip. */
                skip?: number;
                /** @description Maximum rows to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UserRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users.provision_user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProvision"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users.get_user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users.update_user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserAdminUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users.deactivate_user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users.reactivate_user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users.reset_user_password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPasswordReset"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
