"""``terp api-docs`` — generate the public-API contract from the live kernel.

Writes two artefacts from the *live* ``terp.core`` surface (and the ``terp.arch`` rule
registry), so they cannot drift from the package: ``platform-api.md`` (a grouped
reference) and ``terp_core.pyi`` (a flat stub of the semver-public names). An agent in
a consumer repo reads the generated reference instead of guessing the API.
"""

from __future__ import annotations

import ast
import importlib
import inspect
import pathlib

_KIND_CLASS = "class"
_KIND_FUNCTION = "function"
_KIND_VALUE = "value"


class _StubDefault:
    """A placeholder whose ``repr`` is ``...`` so a stub renders the ``.pyi`` default idiom."""

    def __repr__(self) -> str:
        return "..."


_STUB_DEFAULT = _StubDefault()


def _kind(value: object) -> str:
    if inspect.isclass(value):
        return _KIND_CLASS
    if inspect.isfunction(value) or inspect.isbuiltin(value):
        return _KIND_FUNCTION
    return _KIND_VALUE


def _summary(value: object) -> str:
    """The first line of the object's docstring, or an empty string."""
    doc = inspect.getdoc(value)
    return doc.splitlines()[0].strip() if doc else ""


def _signature(value: object) -> str:
    try:
        return str(inspect.signature(value))  # type: ignore[arg-type]
    except (TypeError, ValueError):  # pragma: no cover - defensive; kernel sigs resolve
        return "(...)"


def _stub_signature(value: object) -> str:
    """A stub-safe signature: real parameter names + annotations, defaults shown as ``...``.

    ``inspect.signature`` renders a default by ``repr``, so a non-literal default (a
    function or object — e.g. ``principal_provider=get_principal``) would emit unparseable
    text (``=<function ...>``). Replacing every default with the ``...`` placeholder keeps
    the stub the valid, idiomatic ``.pyi`` form; a signature that cannot be introspected
    falls back to ``(...)``.
    """
    try:
        sig = inspect.signature(value)  # type: ignore[arg-type]
    except (TypeError, ValueError):  # pragma: no cover - defensive; kernel sigs resolve
        return "(...)"
    params = [
        param.replace(default=_STUB_DEFAULT)
        if param.default is not inspect.Parameter.empty
        else param
        for param in sig.parameters.values()
    ]
    rendered = str(sig.replace(parameters=params))
    try:
        ast.parse(f"def _stub{rendered}: ...")
    except SyntaxError:  # pragma: no cover - defensive; annotations are stringized refs
        return "(...)"
    return rendered


def _public_surface() -> list[tuple[str, str, object]]:
    """``(name, kind, value)`` for every name in ``terp.core.__all__``, sorted."""
    core = importlib.import_module("terp.core")
    rows: list[tuple[str, str, object]] = []
    for name in sorted(core.__all__):
        value = getattr(core, name)
        rows.append((name, _kind(value), value))
    return rows


def _markdown(rows: list[tuple[str, str, object]]) -> str:
    lines = [
        "# Terp platform API (generated)",
        "",
        "The semver-public surface of `terp.core`, generated by `terp api-docs` — do not",
        "edit by hand. Import only these names; everything else is internal.",
        "",
    ]
    for kind, heading in ((_KIND_CLASS, "Classes"), (_KIND_FUNCTION, "Functions"), (_KIND_VALUE, "Values")):
        members = [(name, value) for name, member_kind, value in rows if member_kind == kind]
        lines.append(f"## {heading}")
        lines.append("")
        for name, value in members:
            sig = _signature(value) if kind == _KIND_FUNCTION else ""
            summary = _summary(value)
            lines.append(f"- `{name}{sig}`" + (f" — {summary}" if summary else ""))
        lines.append("")
    return "\n".join(lines)


def _stub(rows: list[tuple[str, str, object]]) -> str:
    lines = ["# Generated by `terp api-docs` — the terp.core public surface. Do not edit.", "from typing import Any", ""]
    for name, kind, value in rows:
        if kind == _KIND_CLASS:
            lines.append(f"class {name}: ...")
        elif kind == _KIND_FUNCTION:
            # Emit the *real* signature (parameter names + annotations, defaults as `...`)
            # so the stub is a usable contract, not a content-free `(*args, **kwargs) -> Any`.
            lines.append(f"def {name}{_stub_signature(value)}: ...")
        else:
            lines.append(f"{name}: Any")
    return "\n".join(lines) + "\n"


def api_docs(out_dir: str | pathlib.Path = "docs") -> list[pathlib.Path]:
    """Write ``platform-api.md`` + ``terp_core.pyi`` into *out_dir*; return their paths."""
    rows = _public_surface()
    destination = pathlib.Path(out_dir)
    destination.mkdir(parents=True, exist_ok=True)
    markdown = destination / "platform-api.md"
    stub = destination / "terp_core.pyi"
    markdown.write_text(_markdown(rows), encoding="utf-8")
    stub.write_text(_stub(rows), encoding="utf-8")
    return [markdown, stub]
