"""``terp env`` — the inner loop's missing command over ``.app.env``.

Both halves of the platform had a values story for a **deployed** environment and
neither had one for the machine the code is written on. A deploy tool renders and
seals the file per environment; the documented route for a developer was ``cp
.app.env.example .app.env`` and a text editor. So the only seam in the inner loop
was a hand-maintained file, which is exactly the pressure that produces an
undeclared side file no manifest governs.

Six subcommands, and the manifest is the allow-list in every one of them:

* ``init``    — create ``.app.env`` from the declarations (defaults filled in).
* ``set``     — set one or more ``NAME=value`` pairs.
* ``unset``   — remove names.
* ``list``    — what is set, what is missing, what is declared and empty.
* ``check``   — is this file usable, and does it satisfy the manifest?
* ``example`` — render ``.app.env.example`` FROM the declarations.

Two rules run through all of them.

**An undeclared name is refused**, unless ``--declare`` adds it to the manifest in
the same breath. ``environment.schema.json`` is what a deploy tool renders and
what ``env-seams`` checks; a value under a name it does not declare reaches no
deployed environment at all, so writing one silently would be the local file
quietly disagreeing with every other environment. Refusing it, and offering the
one flag that makes it real, is the difference between a guard and an obstacle.

**A secret's value is never printed.** ``"format": "secret"`` means the value
belongs in a sealed store or a developer's own file, not in terminal scrollback,
a screen share, or a CI log. ``list`` shows that it is set, never what it is.

``example`` is the generator half of the ``env-seams`` parity check: with it, an
app satisfies that check by running a command instead of hand-maintaining a third
file. Deliberately NOT in a verify profile — ``env-seams`` already gates the seam,
and this is a developer's command, not a gate.
"""

from __future__ import annotations

import json
import pathlib

from terp.cli.envschema import (
    APP_ENV_FILE,
    APP_ENV_SCHEMA_FILE,
    MAX_PROPERTIES,
    PLATFORM_OWNED_NAMES,
    _NAME_RE,
    declared_variables,
    manifest_findings,
    rendered_files,
)
from terp.cli.envseams import APP_ENV_EXAMPLE_FILE, parse_dotenv

#: What a declared-secret variable renders as wherever a value would go.
MASKED = "********"

#: The header of a generated example file. It names its own generator, because the
#: first question a reader has about a checked-in file is whether editing it sticks.
_EXAMPLE_HEADER = """\
# App-declared runtime variables — copy to `.app.env` to run the local workbench
# on the same seam the deployed environments use:
#
#     cp {example} {live}
#
# Generated by `terp env example` from {manifest}, which is the allow-list: a name
# here that is not declared there reaches no deployed environment. Re-run that
# command after changing a declaration rather than editing this file by hand.
#
# `.app.env` is gitignored and may hold secrets. This file is committed, so a
# variable declared `"format": "secret"` appears here with an EMPTY value."""


def _required_names(root: pathlib.Path) -> set[str]:
    """The manifest's required names — a DOCUMENT-level array, not a per-property
    field, which is where the dialect actually puts them."""
    path = root / APP_ENV_SCHEMA_FILE
    if not path.is_file():
        return set()
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return set()
    required = document.get("required") if isinstance(document, dict) else None
    return {name for name in required if isinstance(name, str)} if isinstance(
        required, list
    ) else set()


def _write_live(
    root: pathlib.Path, values: dict[str, str], *, file: str = APP_ENV_FILE
) -> None:
    """Write one rendered env file owner-only.

    These are the files in the seam that hold real secret VALUES — the example
    is committed with them blank, and every deployed environment keeps its own in
    a sealed store. A default-permission write leaves an app's credentials
    readable by every other account on the machine, which is a weaker default
    than the deploy path already holds itself to, for the same content.

    ``chmod`` is called unconditionally rather than guarded: the file was just
    written through this same path, so a permission change on it cannot fail for
    a reason a guard could sensibly swallow. On Windows it narrows what it can
    and is a no-op for the rest, exactly as ``pathlib`` documents.

    *file* is a name, never a path, and every caller takes it from
    :func:`rendered_files` — so a per-service render lands beside the shared one and
    inherits these same permissions instead of a second, laxer write path. That matters
    more here than for the shared file: the whole point of scoping a variable is that it
    holds a credential the rest of the app should not see.
    """
    path = root / file
    path.write_text(_render(values), encoding="utf-8")
    path.chmod(0o600)


def _by_file(declared: dict[str, dict]) -> dict[str, list[str]]:
    """Rendered file name -> the declared names that belong in it, both sorted.

    The renderer's half of :func:`rendered_files`. A name scoped to two services appears
    under both of their files, because compose forwards one file per service and a value
    two services need has to exist in each.

    A file with no names is absent rather than empty: an app that scopes nothing must
    write exactly the one file it wrote before the field existed, and empty per-service
    entries would have ``terp env init`` create files no service forwards and nobody
    fills in.
    """
    grouped: dict[str, list[str]] = {}
    for name, prop in sorted(declared.items()):
        for file in sorted(rendered_files(prop)):
            grouped.setdefault(file, []).append(name)
    return grouped


def _secret(prop: dict) -> bool:
    """Whether a declaration marks a write-only secret."""
    return prop.get("format") == "secret"


def _default_of(prop: dict) -> str:
    """A declaration's starting value: empty for a secret, and empty for a JSON
    ``null`` — which ``str()`` would otherwise render as the literal ``None``, a
    truthy string that then reads as "already filled in" everywhere downstream."""
    if _secret(prop):
        return ""
    default = prop.get("default", "")
    return "" if default is None else str(default)


def _render(values: dict[str, str], *, header: str = "") -> str:
    """A ``.app.env`` body: one ``KEY=value`` per line, quoted when it has to be.

    A line break is ESCAPED, not refused. Compose's reader ends an unquoted value
    at the break, but it also interprets ``\\n`` inside double quotes — and
    :func:`parse_dotenv` produces such a value, so a certificate or a private key
    round-trips. Refusing it here instead would mean a file this tool itself can
    read becomes one it will not touch, permanently.
    """
    lines = [header] if header else []
    for name, value in values.items():
        escaped = (
            value.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
            .replace("\r", "\\r")
        )
        needs_quotes = (
            escaped != value
            or value != value.strip()
            or any(character in value for character in ' \t#\'$')
        )
        lines.append(f'{name}="{escaped}"' if needs_quotes else f"{name}={value}")
    return "\n".join(lines) + "\n"


def _read(
    root: pathlib.Path, *, file: str = APP_ENV_FILE
) -> tuple[dict[str, str], list[tuple[int, str]]]:
    path = root / file
    if not path.is_file():
        return {}, []
    return parse_dotenv(path.read_text(encoding="utf-8"))


def _present_renders(root: pathlib.Path) -> set[str]:
    """Per-service env files that exist on disk, whatever the manifest says now.

    ``.app.env`` and ``.app.env.example`` do not match this glob — neither is
    ``.app.<something>.env`` — so it returns the scoped renders and nothing else.
    """
    return {path.name for path in root.glob(".app.*.env")}


def _read_every(
    root: pathlib.Path, declared: dict[str, dict]
) -> tuple[dict[str, dict[str, str]], list[tuple[int, str]]]:
    """Every env file this seam has a stake in: ``({file: values}, problems)``.

    Three sources, unioned, and the third is the one that is easy to leave out:

    * the shared ``.app.env``, **always**. It is where an undeclared value ends up (in
      practice a misspelling of a declared name), and reading only the files the
      declarations imply would make that value invisible to an app whose declarations
      happen to all be scoped — or to one that declares nothing at all.
    * every file the declarations imply, so a name is judged against the file it is
      routed to even before that file exists.
    * every per-service render already on disk. Not tidiness: a ``.app.worker.env``
      left behind after its scope was removed still holds the credential it was created
      for, and a command that cannot see it can neither report it nor clear it.

    Files that do not exist read as empty, exactly as the single file always has — a
    half-initialised seam is the normal state between `terp env init` and the first
    value being filled in, not a defect to report.

    Problems from every file are pooled, because :func:`_refuse_unreadable` speaks for
    the whole command: a value the parser cannot read in the worker's file makes `terp
    env set` on a shared name just as unsafe, since the write rewrites the file it could
    not read.
    """
    per_file: dict[str, dict[str, str]] = {}
    problems: list[tuple[int, str]] = []
    for file in sorted({APP_ENV_FILE, *_by_file(declared), *_present_renders(root)}):
        values, file_problems = _read(root, file=file)
        per_file[file] = values
        problems.extend(file_problems)
    return per_file, problems


def _refuse_unusable_manifest(root: pathlib.Path) -> None:
    """Stop before touching values if the manifest itself is not usable.

    A deploy tool's reader fails closed on the WHOLE file, so a manifest with one
    defect declares nothing at all. Editing values against it would be arranging
    furniture in a house with no walls.
    """
    defects = manifest_findings(root)
    if not defects:
        return
    lines = [f"{APP_ENV_SCHEMA_FILE} is not usable as written:"]
    for defect in defects:
        subject = f"{defect.subject} " if defect.subject else ""
        lines.append(f"  {subject}{defect.detail}")
    lines.append("")
    lines.append("Fix the manifest first: every declaration in it is dropped until then.")
    raise SystemExit("\n".join(lines))


def _declare(root: pathlib.Path, names: list[str]) -> None:
    """Add *names* to the manifest as plain strings, preserving what is there.

    Held to the manifest dialect FIRST, because the reader on the other side fails
    closed on the whole file: one name it refuses and every declaration in the file
    is dropped — the app's secrets included. A convenience flag that can brick the
    manifest is not a convenience, so a name that would not survive the reader is
    refused here, with the reason, before anything is written.
    """
    refused = []
    for name in names:
        if not _NAME_RE.fullmatch(name):
            refused.append(f"{name}: must be UPPER_SNAKE (a letter, then letters, "
                           "digits and underscores; at most 64 characters)")
        elif name in PLATFORM_OWNED_NAMES:
            refused.append(f"{name}: is platform-owned — one owner per variable")
        elif name.startswith("VITE_"):
            refused.append(
                f"{name}: is a frontend build-time variable, baked at image build; "
                "it cannot be injected at run time"
            )
    if refused:
        raise SystemExit(
            "cannot declare:\n  " + "\n  ".join(refused) + "\n"
            f"  {APP_ENV_SCHEMA_FILE}'s reader fails closed on the WHOLE file, so "
            "writing one of these would drop every declaration in it."
        )
    path = root / APP_ENV_SCHEMA_FILE
    if path.is_file():
        document = json.loads(path.read_text(encoding="utf-8"))
    else:
        document = {"type": "object", "properties": {}, "required": []}
    properties = document.setdefault("properties", {})
    for name in names:
        properties.setdefault(name, {"type": "string"})
    if len(properties) > MAX_PROPERTIES:
        raise SystemExit(
            f"{APP_ENV_SCHEMA_FILE} would declare {len(properties)} variables, over "
            f"the dialect's limit of {MAX_PROPERTIES} — the reader drops the whole "
            "file past it"
        )
    path.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")


def _check_names(
    root: pathlib.Path, names: list[str], *, declare: bool
) -> dict[str, dict]:
    """The declarations, after refusing (or adopting) names the manifest lacks."""
    declared = declared_variables(root)
    unknown = [name for name in names if name not in declared]
    if not unknown:
        return declared
    if not declare:
        raise SystemExit(
            f"{', '.join(unknown)}: not declared in {APP_ENV_SCHEMA_FILE}.\n"
            "  That manifest is what a deploy tool renders and what `terp verify "
            "--only env-seams` checks, so a value under an undeclared name reaches "
            "no deployed environment.\n"
            "  Declare it first, or re-run with --declare to add it as a string."
        )
    _declare(root, unknown)
    return declared_variables(root)


def run_env_command(
    *,
    action: str,
    root: str = ".",
    names: list[str] | None = None,
    declare: bool = False,
) -> int:
    """Run one ``terp env`` subcommand; returns the process exit code."""
    project_root = pathlib.Path(root).resolve()
    names = list(names or [])
    # Every action, `example` included: an unusable manifest declares NOTHING, so
    # rendering the example from it would replace the committed file with an empty
    # one and report success. That is the loudest possible way to lose a file.
    _refuse_unusable_manifest(project_root)
    if action == "example":
        return _example(project_root)
    if action == "init":
        return _init(project_root)
    if action == "list":
        return _list(project_root)
    if action == "check":
        return _check(project_root)
    if action == "set":
        return _set(project_root, names, declare=declare)
    if action == "unset":
        return _unset(project_root, names)
    raise SystemExit(f"unknown action {action!r}")


def _init(root: pathlib.Path) -> int:
    """Create every rendered env file from the declarations, defaults filled in."""
    declared = declared_variables(root)
    if not declared:
        raise SystemExit(
            f"{APP_ENV_SCHEMA_FILE} declares no variables, so there is nothing to "
            f"put in {APP_ENV_FILE} yet"
        )
    grouped = _by_file(declared)
    # Refuse if ANY target exists, and name it. Writing the missing files around an
    # existing one would silently re-render half a seam whose other half a developer has
    # already filled in by hand -- and the surviving file is exactly where the secrets
    # are, so a partial init is the one outcome with no safe recovery.
    existing = [file for file in sorted(grouped) if (root / file).exists()]
    if existing:
        # Agrees with its own subject: "already exist(s)" is the shape that makes a
        # refusal read like a template rather than a sentence about this app.
        verb = "already exists" if len(existing) == 1 else "already exist"
        raise SystemExit(
            f"{', '.join(existing)} {verb} — `terp env set` changes a value, and "
            "`terp env list` shows what is in it"
        )
    empty: list[str] = []
    for file, names in sorted(grouped.items()):
        values = {name: _default_of(declared[name]) for name in names}
        _write_live(root, values, file=file)
        empty.extend(name for name, value in values.items() if not value)
        print(f"wrote {file} with {len(values)} declared variable(s)")
    if empty:
        # `sorted(set(...))`: a name scoped to two services is written to two files and
        # is still one thing to fill in.
        print(f"  still to fill in: {', '.join(sorted(set(empty)))}")
    return 0


def _set(root: pathlib.Path, pairs: list[str], *, declare: bool) -> int:
    parsed: dict[str, str] = {}
    for pair in pairs:
        name, separator, value = pair.partition("=")
        if not separator:
            raise SystemExit(f"{pair!r}: expected NAME=value")
        parsed[name.strip()] = value
    if not parsed:
        raise SystemExit("nothing to set — pass one or more NAME=value pairs")
    declared = _check_names(root, list(parsed), declare=declare)
    per_file, problems = _read_every(root, declared)
    _refuse_unreadable(problems)
    # Route each name to the file(s) it is rendered into, never to the one it happens to
    # be sitting in: a declaration that has just been scoped has its old value in the
    # shared file, and writing the new one there again would leave the worker's file --
    # the only one its service forwards -- untouched.
    touched: dict[str, dict[str, str]] = {}
    for name, value in parsed.items():
        for file in sorted(rendered_files(declared.get(name, {}))):
            target = touched.setdefault(file, dict(per_file.get(file, {})))
            target[name] = value
    for file, values in sorted(touched.items()):
        _write_live(root, values, file=file)
    for name in parsed:
        shown = MASKED if _secret(declared.get(name, {})) else parsed[name]
        files = ", ".join(sorted(rendered_files(declared.get(name, {}))))
        # The file is named only when it is not the shared one, so an app that scopes
        # nothing reads exactly as it did.
        suffix = "" if files == APP_ENV_FILE else f"   -> {files}"
        print(f"{name}={shown}{suffix}")
    return 0


def _unset(root: pathlib.Path, names: list[str]) -> int:
    if not names:
        raise SystemExit("nothing to unset — pass one or more names")
    declared = declared_variables(root)
    per_file, problems = _read_every(root, declared)
    _refuse_unreadable(problems)
    # Removed from EVERY file that holds it, including one it no longer belongs in: an
    # unset whose value survives in a file the manifest has stopped routing to is a
    # credential the developer believes they have deleted.
    removed = {name for name in names if any(name in v for v in per_file.values())}
    for file, values in sorted(per_file.items()):
        if not any(name in values for name in names):
            continue
        for name in names:
            values.pop(name, None)
        _write_live(root, values, file=file)
    missing = [name for name in names if name not in removed]
    print(f"removed {len(removed)} of {len(names)} name(s)")
    if missing:
        print(f"  not set anyway: {', '.join(missing)}")
    return 0


def _list(root: pathlib.Path) -> int:
    """Every declared name and whether it is supplied — never a secret's value."""
    declared = declared_variables(root)
    per_file, problems = _read_every(root, declared)
    _refuse_unreadable(problems)
    if not declared and not any(per_file.values()):
        print(f"{APP_ENV_SCHEMA_FILE} declares nothing and {APP_ENV_FILE} is empty")
        return 0
    # Grouped by file, and headed only when there is more than one: the grouping IS the
    # answer for a scoped app ("which service sees this"), and a heading over the single
    # shared file would be furniture in front of the same list as before.
    #
    # Over the files that EXIST, for the reason `_check` iterates them: a value in a
    # file no declaration routes to has to be listed, and it is listed under the file
    # holding it rather than in a trailing block, because which file it is in is the
    # first thing the reader needs in order to delete it.
    grouped = _by_file(declared)
    multi = len(per_file) > 1
    for file in sorted(per_file):
        values = per_file[file]
        names = grouped.get(file, [])
        if multi:
            print(f"  {file}")
        for name in names:
            prop = declared[name]
            if name not in values or values[name] == "":
                shown = "<unset>"
            elif _secret(prop):
                shown = MASKED
            else:
                shown = values[name]
            print(f"  {name:<32} {shown}")
        for name in sorted(set(values) - set(names)):
            print(f"  {name:<32} (not declared — reaches no deployed environment)")
    return 0


def _check(root: pathlib.Path) -> int:
    """Are the rendered files readable, and do they satisfy the manifest?

    Judged per file, and each name only against the file(s) it is rendered into. A
    shared name is not "missing" from the worker's file — nothing routes it there — and
    reporting it would make a correctly scoped app read as broken in proportion to how
    many services it has.
    """
    declared = declared_variables(root)
    per_file, problems = _read_every(root, declared)
    findings = [f"line {number}: {problem}" for number, problem in problems]
    grouped = _by_file(declared)
    required = _required_names(root)
    # Iterate the files that EXIST (plus the ones the declarations imply), not just the
    # implied ones: a value in a file no declaration routes to is the case this whole
    # command is for, and looping over the manifest's own view would be asking the
    # manifest whether the manifest is being followed.
    multi = len(per_file) > 1
    for file in sorted(per_file):
        values = per_file[file]
        names = grouped.get(file, [])
        # The file is named only for a scoped app, so single-file output is unchanged.
        where = f" ({file})" if multi else ""
        for name in names:
            if name not in values:
                findings.append(f"{name}: declared but not set here{where}")
            elif name in required and not values[name]:
                findings.append(f"{name}: required by the manifest and empty here{where}")
        for name in sorted(set(values) - set(names)):
            if name in declared:
                # Declared, but routed elsewhere — a stale copy left behind when the
                # declaration was scoped or re-scoped. Saying "not declared" here would
                # send the reader to the manifest to add something already in it.
                elsewhere = ", ".join(sorted(rendered_files(declared[name])))
                findings.append(
                    f"{name}: set here{where} but rendered into {elsewhere}, so this "
                    "copy reaches no deployed environment"
                )
            else:
                findings.append(
                    f"{name}: set here{where} but not declared, so it reaches no "
                    "deployed environment"
                )
    files = ", ".join(sorted(per_file))
    if not findings:
        print(f"{files} supplies every declared variable")
        return 0
    print(f"{files} does not agree with {APP_ENV_SCHEMA_FILE}:")
    for finding in findings:
        print(f"  {finding}")
    return 1


def _example(root: pathlib.Path) -> int:
    """Render ``.app.env.example`` FROM the declarations.

    The generator half of the ``env-seams`` parity check: an app satisfies that
    check by running this instead of hand-maintaining a third file.
    """
    declared = declared_variables(root)
    if not declared:
        # `manifest_findings` is empty for a manifest that is merely ABSENT, so the
        # usability guard does not cover this — and this command overwrites a
        # COMMITTED file. Replacing it with a header and reporting success is the
        # loudest possible way to lose it, so refuse instead. (`init` already
        # refuses here; `example` writes the more valuable file of the two.)
        raise SystemExit(
            f"{APP_ENV_SCHEMA_FILE} declares no variables, so there is nothing to "
            f"put in {APP_ENV_EXAMPLE_FILE} — writing it now would replace whatever "
            "is committed there with an empty file"
        )
    header = _EXAMPLE_HEADER.format(
        example=APP_ENV_EXAMPLE_FILE, live=APP_ENV_FILE, manifest=APP_ENV_SCHEMA_FILE
    )
    lines = [header, ""]
    for name, prop in sorted(declared.items()):
        title = prop.get("title") or prop.get("description")
        if title:
            lines.append(f"# {title}")
        if _secret(prop):
            lines.append("# Declared secret: leave this empty, it is committed.")
            lines.append(f"{name}=")
        else:
            # Rendered through the same quoting the live file uses: a default
            # containing ` #` would otherwise be truncated the moment this file is
            # copied to .app.env, and a non-string default would render as Python.
            lines.append(_render({name: _default_of(prop)}).strip())
        lines.append("")
    (root / APP_ENV_EXAMPLE_FILE).write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {APP_ENV_EXAMPLE_FILE} from {len(declared)} declaration(s)")
    return 0


def _refuse_unreadable(problems: list[tuple[int, str]]) -> None:
    """A file this parser cannot read is one compose cannot read either.

    Rewriting it from a partial parse would silently drop whatever failed, so the
    only safe move is to stop and name the line.
    """
    if not problems:
        return
    lines = [f"{APP_ENV_FILE} cannot be read the way compose reads it:"]
    lines += [f"  line {number}: {problem}" for number, problem in problems]
    lines.append("")
    lines.append("Fix those lines first: rewriting the file now would drop them.")
    raise SystemExit("\n".join(lines))


__all__ = ["run_env_command"]
