"""``terp env`` — the inner loop's missing command over ``.app.env``.

Both halves of the platform had a values story for a **deployed** environment and
neither had one for the machine the code is written on. A deploy tool renders and
seals the file per environment; the documented route for a developer was ``cp
.app.env.example .app.env`` and a text editor. So the only seam in the inner loop
was a hand-maintained file, which is exactly the pressure that produces an
undeclared side file no manifest governs.

Six subcommands, and the manifest is the allow-list in every one of them:

* ``init``    — create ``.app.env`` from the declarations (defaults filled in).
* ``set``     — set one or more ``NAME=value`` pairs.
* ``unset``   — remove names.
* ``list``    — what is set, what is missing, what is declared and empty.
* ``check``   — is this file usable, and does it satisfy the manifest?
* ``example`` — render ``.app.env.example`` FROM the declarations.

Two rules run through all of them.

**An undeclared name is refused**, unless ``--declare`` adds it to the manifest in
the same breath. ``environment.schema.json`` is what a deploy tool renders and
what ``env-seams`` checks; a value under a name it does not declare reaches no
deployed environment at all, so writing one silently would be the local file
quietly disagreeing with every other environment. Refusing it, and offering the
one flag that makes it real, is the difference between a guard and an obstacle.

**A secret's value is never printed.** ``"format": "secret"`` means the value
belongs in a sealed store or a developer's own file, not in terminal scrollback,
a screen share, or a CI log. ``list`` shows that it is set, never what it is.

``example`` is the generator half of the ``env-seams`` parity check: with it, an
app satisfies that check by running a command instead of hand-maintaining a third
file. Deliberately NOT in a verify profile — ``env-seams`` already gates the seam,
and this is a developer's command, not a gate.
"""

from __future__ import annotations

import json
import pathlib

from terp.cli.envschema import APP_ENV_SCHEMA_FILE, declared_variables, manifest_findings
from terp.cli.envseams import APP_ENV_EXAMPLE_FILE, APP_ENV_FILE, parse_dotenv

#: What a declared-secret variable renders as wherever a value would go.
MASKED = "********"

#: The header of a generated example file. It names its own generator, because the
#: first question a reader has about a checked-in file is whether editing it sticks.
_EXAMPLE_HEADER = """\
# App-declared runtime variables — copy to `.app.env` to run the local workbench
# on the same seam the deployed environments use:
#
#     cp {example} {live}
#
# Generated by `terp env example` from {manifest}, which is the allow-list: a name
# here that is not declared there reaches no deployed environment. Re-run that
# command after changing a declaration rather than editing this file by hand.
#
# `.app.env` is gitignored and may hold secrets. This file is committed, so a
# variable declared `"format": "secret"` appears here with an EMPTY value."""


def _secret(prop: dict) -> bool:
    """Whether a declaration marks a write-only secret."""
    return prop.get("format") == "secret"


def _render(values: dict[str, str], *, header: str = "") -> str:
    """A ``.app.env`` body: one ``KEY=value`` per line, quoted when it has to be."""
    lines = [header] if header else []
    for name, value in values.items():
        needs_quotes = value != value.strip() or any(
            character in value for character in ' \t#"\'$'
        )
        if needs_quotes:
            escaped = value.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'{name}="{escaped}"')
        else:
            lines.append(f"{name}={value}")
    return "\n".join(lines) + "\n"


def _read(root: pathlib.Path) -> tuple[dict[str, str], list[tuple[int, str]]]:
    path = root / APP_ENV_FILE
    if not path.is_file():
        return {}, []
    return parse_dotenv(path.read_text(encoding="utf-8"))


def _refuse_unusable_manifest(root: pathlib.Path) -> None:
    """Stop before touching values if the manifest itself is not usable.

    A deploy tool's reader fails closed on the WHOLE file, so a manifest with one
    defect declares nothing at all. Editing values against it would be arranging
    furniture in a house with no walls.
    """
    defects = manifest_findings(root)
    if not defects:
        return
    lines = [f"{APP_ENV_SCHEMA_FILE} is not usable as written:"]
    for defect in defects:
        subject = f"{defect.subject} " if defect.subject else ""
        lines.append(f"  {subject}{defect.detail}")
    lines.append("")
    lines.append("Fix the manifest first: every declaration in it is dropped until then.")
    raise SystemExit("\n".join(lines))


def _declare(root: pathlib.Path, names: list[str]) -> None:
    """Add *names* to the manifest as plain strings, preserving what is there."""
    path = root / APP_ENV_SCHEMA_FILE
    if path.is_file():
        document = json.loads(path.read_text(encoding="utf-8"))
    else:
        document = {"type": "object", "properties": {}, "required": []}
    properties = document.setdefault("properties", {})
    for name in names:
        properties.setdefault(name, {"type": "string"})
    path.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")


def _check_names(
    root: pathlib.Path, names: list[str], *, declare: bool
) -> dict[str, dict]:
    """The declarations, after refusing (or adopting) names the manifest lacks."""
    declared = declared_variables(root)
    unknown = [name for name in names if name not in declared]
    if not unknown:
        return declared
    if not declare:
        raise SystemExit(
            f"{', '.join(unknown)}: not declared in {APP_ENV_SCHEMA_FILE}.\n"
            "  That manifest is what a deploy tool renders and what `terp verify "
            "--only env-seams` checks, so a value under an undeclared name reaches "
            "no deployed environment.\n"
            "  Declare it first, or re-run with --declare to add it as a string."
        )
    _declare(root, unknown)
    return declared_variables(root)


def run_env_command(
    *,
    action: str,
    root: str = ".",
    names: list[str] | None = None,
    declare: bool = False,
) -> int:
    """Run one ``terp env`` subcommand; returns the process exit code."""
    project_root = pathlib.Path(root).resolve()
    names = list(names or [])
    if action == "example":
        return _example(project_root)
    _refuse_unusable_manifest(project_root)
    if action == "init":
        return _init(project_root)
    if action == "list":
        return _list(project_root)
    if action == "check":
        return _check(project_root)
    if action == "set":
        return _set(project_root, names, declare=declare)
    if action == "unset":
        return _unset(project_root, names)
    raise SystemExit(f"unknown action {action!r}")


def _init(root: pathlib.Path) -> int:
    """Create ``.app.env`` from the declarations, defaults filled in."""
    path = root / APP_ENV_FILE
    if path.exists():
        raise SystemExit(
            f"{APP_ENV_FILE} already exists — `terp env set` changes a value, and "
            "`terp env list` shows what is in it"
        )
    declared = declared_variables(root)
    if not declared:
        raise SystemExit(
            f"{APP_ENV_SCHEMA_FILE} declares no variables, so there is nothing to "
            "put in {APP_ENV_FILE} yet"
        )
    values = {
        name: "" if _secret(prop) else str(prop.get("default", ""))
        for name, prop in declared.items()
    }
    path.write_text(_render(values), encoding="utf-8")
    empty = sorted(name for name, value in values.items() if not value)
    print(f"wrote {APP_ENV_FILE} with {len(values)} declared variable(s)")
    if empty:
        print(f"  still to fill in: {', '.join(empty)}")
    return 0


def _set(root: pathlib.Path, pairs: list[str], *, declare: bool) -> int:
    parsed: dict[str, str] = {}
    for pair in pairs:
        name, separator, value = pair.partition("=")
        if not separator:
            raise SystemExit(f"{pair!r}: expected NAME=value")
        parsed[name.strip()] = value
    if not parsed:
        raise SystemExit("nothing to set — pass one or more NAME=value pairs")
    declared = _check_names(root, list(parsed), declare=declare)
    values, problems = _read(root)
    _refuse_unreadable(problems)
    values.update(parsed)
    (root / APP_ENV_FILE).write_text(_render(values), encoding="utf-8")
    for name in parsed:
        shown = MASKED if _secret(declared.get(name, {})) else parsed[name]
        print(f"{name}={shown}")
    return 0


def _unset(root: pathlib.Path, names: list[str]) -> int:
    if not names:
        raise SystemExit("nothing to unset — pass one or more names")
    values, problems = _read(root)
    _refuse_unreadable(problems)
    missing = [name for name in names if name not in values]
    for name in names:
        values.pop(name, None)
    (root / APP_ENV_FILE).write_text(_render(values), encoding="utf-8")
    print(f"removed {len(names) - len(missing)} of {len(names)} name(s)")
    if missing:
        print(f"  not set anyway: {', '.join(missing)}")
    return 0


def _list(root: pathlib.Path) -> int:
    """Every declared name and whether it is supplied — never a secret's value."""
    declared = declared_variables(root)
    values, problems = _read(root)
    _refuse_unreadable(problems)
    if not declared and not values:
        print(f"{APP_ENV_SCHEMA_FILE} declares nothing and {APP_ENV_FILE} is empty")
        return 0
    for name, prop in sorted(declared.items()):
        if name not in values or values[name] == "":
            print(f"  {name:<32} <unset>")
        elif _secret(prop):
            print(f"  {name:<32} {MASKED}")
        else:
            print(f"  {name:<32} {values[name]}")
    undeclared = sorted(set(values) - set(declared))
    for name in undeclared:
        print(f"  {name:<32} (not declared — reaches no deployed environment)")
    return 0


def _check(root: pathlib.Path) -> int:
    """Is the file readable, and does it satisfy the manifest?"""
    values, problems = _read(root)
    findings = [f"line {number}: {problem}" for number, problem in problems]
    declared = declared_variables(root)
    for name in sorted(set(declared) - set(values)):
        findings.append(f"{name}: declared but not set here")
    for name in sorted(set(values) - set(declared)):
        findings.append(
            f"{name}: set here but not declared, so it reaches no deployed environment"
        )
    for name, prop in sorted(declared.items()):
        if _secret(prop) and values.get(name):
            continue
        if prop.get("required") and not values.get(name):
            findings.append(f"{name}: required and empty")
    if not findings:
        print(f"{APP_ENV_FILE} supplies every declared variable")
        return 0
    print(f"{APP_ENV_FILE} does not agree with {APP_ENV_SCHEMA_FILE}:")
    for finding in findings:
        print(f"  {finding}")
    return 1


def _example(root: pathlib.Path) -> int:
    """Render ``.app.env.example`` FROM the declarations.

    The generator half of the ``env-seams`` parity check: an app satisfies that
    check by running this instead of hand-maintaining a third file.
    """
    declared = declared_variables(root)
    header = _EXAMPLE_HEADER.format(
        example=APP_ENV_EXAMPLE_FILE, live=APP_ENV_FILE, manifest=APP_ENV_SCHEMA_FILE
    )
    lines = [header, ""]
    for name, prop in sorted(declared.items()):
        title = prop.get("title") or prop.get("description")
        if title:
            lines.append(f"# {title}")
        if _secret(prop):
            lines.append("# Declared secret: leave this empty, it is committed.")
            lines.append(f"{name}=")
        else:
            lines.append(f"{name}={prop.get('default', '')}")
        lines.append("")
    (root / APP_ENV_EXAMPLE_FILE).write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {APP_ENV_EXAMPLE_FILE} from {len(declared)} declaration(s)")
    return 0


def _refuse_unreadable(problems: list[tuple[int, str]]) -> None:
    """A file this parser cannot read is one compose cannot read either.

    Rewriting it from a partial parse would silently drop whatever failed, so the
    only safe move is to stop and name the line.
    """
    if not problems:
        return
    lines = [f"{APP_ENV_FILE} cannot be read the way compose reads it:"]
    lines += [f"  line {number}: {problem}" for number, problem in problems]
    lines.append("")
    lines.append("Fix those lines first: rewriting the file now would drop them.")
    raise SystemExit("\n".join(lines))


__all__ = ["run_env_command"]
